

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug
#        http:
#          server:
#            reactive: debug
#        web:
#          reactive: debug
    reactor:
      netty:
        http:
          client: debug
