
spring:
  cloud:
    function: # ?? ???? ??? ??? ?? spring cloud function ?? ?????? ??, Consumer : input binding, Supplier : output binding, Function : function binding
      definition: printFluxString;sequenceFluxString;mapFluxString