server:
  shutdown: graceful

logging:
  config: classpath:logback.xml
  level:
    reactor.netty:
      http.server: DEBUG
      transport: DEBUG
    io.netty:
      channel: DEBUG
      handler: DEBUG