spring:
  application:
    name: webflux-and-coroutine

  # sub11 - R2DBC + 코루틴 (in-memory H2)
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
