### 정상 응답 1
GET http://localhost:8080/articles/get-1

### 정상 응답 2
GET http://localhost:8080/articles/get-2

### 에러 응답 1
GET http://localhost:8080/articles/error-1
X-Request-ID: aaa

### 에러 응답 2
GET http://localhost:8080/articles/error-2
X-Request-ID: bbb

### post application/json
POST http://localhost:8080/articles/new-1
Content-Type: application/json

{
  "title": "good",
  "content": "content"
}

### post application/x-www-form-urlencoded
POST http://localhost:8080/articles/new-2
Content-Type: application/x-www-form-urlencoded

title=title
    &content=content

### get query parameter
GET http://localhost:8080/articles/new-3?title=title&content=content


### no body response
GET http://localhost:8080/articles/no-body?title=title&content=content

### server sleep, client disconnect (여기서 안되고.. 아래 curl 명령어로 요청보내고 (ctrl+C)로 끊어버려야함)
### curl http://localhost:8080/articles/sleep-and-disconnect-1
GET http://localhost:8080/articles/sleep-and-disconnect-1

### server sleep, client disconnect (여기서 안되고.. 아래 curl 명령어로 요청보내고 (ctrl+C)로 끊어버려야함)
### curl http://localhost:8080/articles/sleep-and-disconnect-2
GET http://localhost:8080/articles/sleep-and-disconnect-2
