server:
  port: 8081
# ?? ??? ?? ??? ??? ???
spring:
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      password: